Network:
  epochs: 20000000
  batch_size: 250 #250
  n_steps: 4 # timestep
  dataset: "hole"
  in_channels: 1
  data_path: "./data"
  lr: 0.0001
  weight_decay: 0.001
  latent_dim: 128
  input_size: 32
  model: "FSVAE" # FSVAE or  FSVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld
 
